spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pears?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      stat-view-servlet:
        login-username: admin
        login-password: 123456


mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

supply:
  jwt:
    secret_key: yuanning
    #过期时间为24个小时
    ttl: 86400000

